force-app/main/default/objects/FT_Products__c/FT_Products__c.object-meta.xml
<CustomObject>
    <label>FT-Products</label>
    <nameField>
        <label>FT-Products Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>FT-Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FT_Products__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>T-Shirts</fullName>
            </value>
            <value>
                <fullName>Trousers</fullName>
            </value>
            <value>
                <fullName>Footwear</fullName>
            </value>
            <value>
                <fullName>Books</fullName>
            </value>
            <value>
                <fullName>Electronics</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/FT_Products__c/fields/featured__c.field-meta.xml
<CustomField>
    <fullName>featured__c</fullName>
    <defaultValue>false</defaultValue>
    <label>featured</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/FT_Products__c/fields/Image_Link2__c.field-meta.xml
<CustomField>
    <fullName>Image_Link2__c</fullName>
    <label>Image Link2</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/FT_Products__c/fields/Image_Link3__c.field-meta.xml
<CustomField>
    <fullName>Image_Link3__c</fullName>
    <label>Image Link3</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/FT_Products__c/fields/Image_Link4__c.field-meta.xml
<CustomField>
    <fullName>Image_Link4__c</fullName>
    <label>Image Link4</label>
    <type>Url</type>
</CustomField>

force-app/main/default/classes/ProductsController.cls
public class ProductsController {

    @AuraEnabled
    public static List<FT_Products__c> getFeaturedProduct(){
        
        List<FT_Products__c> featured = [Select Id,Name,Price__c,Product_Description__c,
                                        Image_Link__c,Image_Link2__c,Image_Link3__c,Category__c,
                                        Image_Link4__c From FT_Products__c Where featured__c = true];
        
        if(!featured.isEmpty()){
            return featured;
        }
        return Null;
    }
}