force-app/main/default/objects/Projects__c/Projects__c.object-meta.xml
<CustomObject>
    <label>Projects</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Projects__c/fields/Technologies_Used__c.field-meta.xml
<CustomField>
    <fullName>Technologies_Used__c</fullName>
    <label>Technologies Used</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Triggers</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Experience Cloud</fullName>
            </value>
            <value>
                <fullName>MongoDb</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PortfolioClassTest.cls
@isTest
public class PortfolioClassTest {
    
    @testSetup static void testMethods(){
         List<Projects__c> pList = new  List<Projects__c>();
            for(Integer i=0;i<3;i++) {
                Projects__c a = new Projects__c(Name='TestProject' + i);
                pList.add(a);
            }
        
        insert pList;
    }
    
    @isTest static void testProjectList(){
        List<Projects__c> pro = [ SELECT Id, Name, Description__c, Technologies_Used__c, Website__c FROM Projects__c ];
        List<Projects__c> p = PortfolioClass.getProjectList();
        
        system.assertEquals(pro, p);   
    }
    
     @isTest static void testProjectLists(){
        
        List<Projects__c> pro = [ SELECT Id, Name, Description__c, Technologies_Used__c, Website__c FROM Projects__c ];
        List<Projects__c> p = ProjectsController.getProjects();
        system.assertEquals(pro, p);   
         
    }

  @isTest static void testProjectListss(){
     
        List<Projects__c> pro = [ SELECT Id, Name, Description__c, Technologies_Used__c, Website__c FROM Projects__c];
      	delete pro;
        List<Projects__c> p = ProjectsController.getProjects();
	    system.assertEquals(p,NULL);   
        
    }


}