force-app/main/default/objects/Projects__c/Projects__c.object-meta.xml
<CustomObject>
    <label>Projects</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Projects__c/fields/Technologies_Used__c.field-meta.xml
<CustomField>
    <fullName>Technologies_Used__c</fullName>
    <label>Technologies Used</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Triggers</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Experience Cloud</fullName>
            </value>
            <value>
                <fullName>MongoDb</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Projects__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>MERN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ProjectsController.cls
public class ProjectsController {
    
    @AuraEnabled(cacheable=true)
    public static List<Projects__c> getProjects(){
        
        List<Projects__c> projectList = [Select Id,Name,Description__c,Technologies_Used__c From Projects__c];
        
        if(!projectList.isEmpty()){
            return projectList;
        }
        return NULL;
    }

    @AuraEnabled(cacheable=true)
    public static List<Projects__c> getProjectsById(String projectType){
        
        List<Projects__c> projectList = [Select Id,Name,Description__c,Type__c,Technologies_Used__c From Projects__c
                                         Where Type__c =: projectType];
        
        if(!projectList.isEmpty()){
            return projectList;
        }
        return NULL;
    }

}