force-app/main/default/objects/Projects__c/Projects__c.object-meta.xml
<CustomObject>
    <label>Projects</label>
    <nameField>
        <label>Projects Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Projects__c/fields/Technologies_Used__c.field-meta.xml
<CustomField>
    <fullName>Technologies_Used__c</fullName>
    <label>Technologies Used</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Triggers</fullName>
            </value>
            <value>
                <fullName>React</fullName>
            </value>
            <value>
                <fullName>Node</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>Experience Cloud</fullName>
            </value>
            <value>
                <fullName>MongoDb</fullName>
            </value>
            <value>
                <fullName>Integration</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PortfolioClass.cls
public without sharing class PortfolioClass {
    
    @AuraEnabled(cacheable=true)
    public static List<Projects__c> getProjectList(){
        List<Projects__c> pro = [ SELECT Id, Name, Description__c, Technologies_Used__c, Website__c FROM Projects__c ];
        system.debug('pro:'+pro);
        return pro;
        
        /*if(!pro.isEmpty()){
            return pro;
        }else{
            return null;
        }*/
        
    }

}